/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.classes

class App(name: String = "App Name", version: String = "0.0.1") {
  val name = name
  val version = version
  var environment: String? = null
    get() {
      return field ?: "Local"
    }

  constructor(name: String, version: String, environment: String) : this(name, version) {
    // any other code that needs to be executed for this constructor
    this.environment = environment
  }
  var number = 0
  // member variables or class properties or fields
  // val name: String = "App Name"
  // val version: String = "0.0.1"

  fun printApp() {
    println("The app name is $name and the version is $version. The environment is $environment")
  }
}

class AnotherClass {}

fun main() {

  // let's talk about creating objects
  val app = App()
  app.printApp()

  val app2 = App("New App Name", "1.0.0")
  app2.printApp()

  val app3 = App("New App Name", "1.0.0", "Development")
  app3.printApp()

  app.environment = "Production"

  app.number = 10
  // app.name = "New App Name"
  // app.version = "1.0.0"
  // println("The app name is: ${app.name} and the version is: ${app.version}")
  // println(app)
}
